import type { Metadata } from 'next'
import React from 'react'
import { Roboto } from 'next/font/google'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'
import Navbar from '@/components/Navbar'
import Alert from '@/components/Alert'
import Footer from '@/components/Footer'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`${roboto.className}`}>
        <Alert />
        <NextTopLoader />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
